name: Deploy addons to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy on VPS via SSH
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: 92.113.147.154
          username: user
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 22
          script: |
            cd /home/user/odoo-18-docker-compose/addons
            git pull origin main
            
