name: Deploy addons to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.8
      with:
        ssh-private-key: ${{ secrets.VPS_SSH_KEY }}

    - name: Deploy on VPS
      run: |
        ssh -o StrictHostKeyChecking=no root@IP_VPS << 'EOF'
          cd /home/user/odoo-18-docker-compose/addons
          git pull origin main
          docker-compose restart odoo
        EOF
